### ISSUE TITLE
Continue implementing the login sequence

### ISSUE THREAD

**Issue by rom1504** [louis030195/PathOfBot#1]
See http://www.blizzhackers.cc/viewtopic.php?t=406445
Things to add in : 
* protocol.json : add new packets
* createClient.json : send correct packet when packet are received

**Comment by rom1504** [comment]
done up to step 11

Remaining 12 -> 50

**Comment by louis030195** [comment]
step 17 : use sha1 hashing algorithm on password

**Comment by rom1504** [comment]
step 20

**Comment by rom1504** [comment]
step 22
next is opening connection 3

**Comment by rom1504** [comment]
step 28

**Comment by rom1504** [comment]
step 42

**Comment by rom1504** [comment]
step 49 reached; to do : 
* [ ] setup boirlerplate for client 4
* [ ] compression

**Comment by rom1504** [comment]
step 50 done

What is step 51 ?

ie what is the next thing to send after https://bnetdocs.org/packet/245 ?

look for some new doc or read other bots code

**Comment by rom1504** [comment]
see https://github.com/dkuwahara/OmegaBot/blob/398128b4cbc96194065da510a7482c521ecf6f90/Connections/Readers/D2gsReader.cs#L202

**Comment by rom1504** [comment]
according to that code https://bnetdocs.org/packet/131/d2gs-gamelogon should be sent

**Comment by louis030195** [comment]
The bot create game but seems to not be inside or stuck somewhere else, the bot is still displayed in the game on my friend list

**Comment by louis030195** [comment]
https://bnetdocs.org/document/28/diablo-ii-game-server-accept-sequence

**Comment by rom1504** [comment]
when bnet down https://gist.github.com/erm/9809361
