### ISSUE TITLE
Join game crash

### ISSUE THREAD

**Issue by louis030195** [louis030195/PathOfBot#13]
**Happen sometimes when joining / creating game**

received packet SID_STARTADVEX3 { status: 1 }
{ status: 1 }
sending packet SID_NOTIFYJOIN { productId: 1,
  productVersion: 14,
  gameName: 'gh',
  gamePassword: 'g' }
sending packet SID_LEAVECHAT {}
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 0.0.0.0:4000
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)

Process finished with exit code 1

**Comment by rom1504** [comment]
it means you connected to a game that doesn't exist or with the wrong password

just try to do the opposite, create the game with the bot
