### ISSUE TITLE
Check field of D2GS_LOGONRESPONSE

### ISSUE THREAD

**Issue by rom1504** [louis030195/PathOfBot#17]

**Comment by louis030195** [comment]
https://bnetdocs.org/packet/177/mcp-creategame

> The comment about the request id being incremented by 0x02 is misstated. The request id is incremented by 0x01 for each MCP_CREATEGAME request and 0x01 for each MCP_JOINGAME request. For example, if the MCP_CREATEGAME request fails, the subsequent request id would be 0x03.

```
clientDiablo.write('MCP_CREATEGAME', {
      requestId: 2,
      difficulty, // NORMAL, TODO : set diff with args
      unknown: 1,
      levelRestrictionDifference: 99,
      maximumPlayers: 8,
      gameName: gameName,
      gamePassword: gamePassword,
      gameDescription: 'gs ' + gameServer
    })
```

requestId should be dynamic, probably the issue with getting kicked by server
