### ISSUE TITLE
compression

### ISSUE THREAD

**Issue by rom1504** [louis030195/PathOfBot#7]
https://github.com/dkuwahara/OmegaBot/blob/master/Compression.cs

https://github.com/epicvrvs/heroin_glands/blob/master/heroin/compression.cpp 

It should be quite doable to just reimplement it. Not too many bitwise operations here.

**Comment by louis030195** [comment]
https://github.com/killerbonzai/BlueVex2

**Comment by rom1504** [comment]
https://dotnetfiddle.net/s0LbT9

**Comment by rom1504** [comment]
https://deck.net/a1648260f60adb3cd354b1df3978bc0b

**Comment by rom1504** [comment]
broken js https://gist.github.com/rom1504/9176b0bfd6a2234d243b2966e3378622

going translated c#

**Comment by rom1504** [comment]
trying to understand whether https://github.com/dkuwahara/OmegaBot/blob/master/Connections/Readers/D2gsReader.cs#L225 or https://redux.bnetdocs.org/?op=doc&did=16 is correct : is there a size header, or does it need to be guessed (as is doing omegabot) ?

**Comment by rom1504** [comment]
heroin is doing exactly the same so it's clearly the thing to do https://github.com/epicvrvs/heroin_glands/blob/master/heroin/compression.cpp

**Comment by rom1504** [comment]
works
